permissions:
  contents: read
name: UV Testing

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    name: UV Tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UV
        run: pip install uv

      - name: Setup a local virtual environment
        run: uv venv

      - uses: actions/cache@v5
        name: Cache virtual environment
        with:
          path: ./.venv
          key: venv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            venv-

      - name: Install the project dependencies
        run: |
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Ensure xdist
        run: |
          source .venv/bin/activate
          uv pip install pytest-xdist

      - name: Run the automated tests
        run: |
          source .venv/bin/activate
          uv run pytest -n 8 --cov-report xml:cov.xml --cov intellifire4py --cov-report term-missing --durations-min=1 --durations=0

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          files: ./cov.xml
